### ISSUE TITLE
Image upload and display in tkinter window

### ISSUE THREAD

**Issue by jl532** [nate-watson80/BME547Final#1]

**Comment by jl532** [comment]
the images display within a matplotlib plotting widget and the file location is displayed within a Qlabel widget! works well.

**Comment by nate-watson80** [comment]
@jl532 FYI -  I am having some difficulties running the code you have developed already. I am thinking that it must be an issue in that you have been developing in conda and I am in PyCharm. I am trying to figure out what is going but just wanted to give you the heads up.

**Comment by nate-watson80** [comment]
@jl532 Follow up - is there a reason you used pyqt instead of tkinter?

**Comment by jl532** [comment]
yeah, i just have code that already works with it
i forked the repo to work on it separately... merging back now

-Jason

**Comment by jl532** [comment]
ok so pull the JL532 branch and install all required packages with pip
install -r requirements.txt and then you'll need mongodb community edition
(download that)

and then everything should work. you'll need to run the server in one
window (python final-server.py) and then the gui in another window (python
GUI-test.py) and it'll work from there

I can give you a quick rundown whenever tonight, lemme know

-Jason

**Comment by nate-watson80** [comment]
Ok great. Thanks for putting a lot in already. I started working on the database stuff tonight

**Comment by jl532** [comment]
oh the database is already good to go actually lol

it's.... a lot. take your time and mess with things
