### ISSUE TITLE
Create a specific module used ONLY for creating a class for MongoDB

### ISSUE THREAD

**Issue by jcoop1219** [nate-watson80/BME547Final#23]
Since MongoDB associates a class with the module which created the class, there can be weirdness if you create the class in one module and then in your unit test module, you create the same-named class.

Instead, just create a singular module for the creation of the class which can then be imported into your other modules.

**Comment by nate-watson80** [comment]
Hey guys - What is the deal with Mongo right now? Are we still running this locally or have we switched over to a cloud-based system.

**Comment by jcoop1219** [comment]
We’re not running locally anymore (we’re running on an Atlas MongoDB database). I think we can close this issue though since we define the Mongo class in final_server.py, and if we ever need to reference that class we can just import the class definition from final_server.py

**Comment by nate-watson80** [comment]
Thanks. ANd ya I agree - lets close it.
