### ISSUE TITLE
Assigning Issues

### ISSUE THREAD

**Issue by dward2** [nate-watson80/BME547Final#40]
@jl532 @nate-watson80 @jcoop1219 You have a good list of issues you are working from.  However, there is no one assigned to any of them.  Please make sure to assign one or more individuals to specific issues/work tasks.

Also, we will be looking at intra-team communications in the comments of the issues.  So, as you are working over the next few days, think about how you share information with each other and how you might be able to do that in the comments of issues.

Finally, who is manav-a?

**Comment by jl532** [comment]
@dward2  We will be working on it! 

Sorry for not asking in advance, but Manav-A is an undergrad in my lab who specifically wrote code that improves the accuracy of the spot/circle finding algorithm-- the unique image processing task that I proposed in our project. I incorporated these improvements into my branch. If this is not okay, we can remove his code.

**Comment by dward2** [comment]
@jl532 Thanks for the answer.  That is fine.  As long as those contributions are restricted to the image-processing algorithms, that is acceptable.

**Comment by jl532** [comment]
@dward2, I wanted to get out in front of this before we officially submit our code:

After inspection to individual commits and contributions to our project code, **Manav-A made non-essential and unprompted changes to the GUI and server code** peripheral to the image-processing algorithms. We are actively undoing the parts he added to to make sure the code is as clean of his influence as possible now. Here's what happened in more detail:

Originally this project was born out of a need in my lab for software that handles this specific image processing task of finding circles within an image. Manav-A was interested in working on the problem as well, and to be frank, he needed a project to work on in lab for a independent research grade. I originally communicated to him that our circle finding algorithm could use a face-lift, and he wished to work on improving it. I had written the majority of the actual specific functionality needed for this project prior to his involvement, and forked the repo to my github to work on it separately, with Manav-A working on that forked repo specifically. When we merged branches together and I merged my changes to this main repo (hosted by Nate), the changes made by Manav-A were integrated as well. This was my fault entirely and I accept all blame for this-- there was a miscommunication with Manav about the scope of his involvement, and I had not noticed the changes he had made to the code prior to my merging my forked changes into our main project code. 

Let me know how best to fix this issue beyond undoing his changes-- I will do what you think is best if this is insufficient.

Sorry for the confusion and major apologies to my teammates @nate-watson80 and @jcoop1219 for roping you guys into this.

**Comment by dward2** [comment]
Thanks for the update.   If you undo his commits, that is sufficient.   If undoing his commits start breaking your code, let me know.  I'd rather keep your code functional than remove all of his additions.

Dr. Ward
________________________________

**Comment by jl532** [comment]
https://github.com/nate-watson80/BME547Final/commits?author=manav-a

Here is the official list of commits by Manav-- the big thing he added was an additional GUI window and we are trying to undo it. There are some variables that get shunted around the UI code and are saved in the db, and may break it...

**Comment by jl532** [comment]
@nate-watson80 was able to remove the additional GUI window without breaking it.
