### ISSUE TITLE
make video of final product

### ISSUE THREAD

**Issue by jl532** [nate-watson80/BME547Final#52]

**Comment by nate-watson80** [comment]
Sorry I accidently closed this.

**Comment by nate-watson80** [comment]
@jl532 @jcoop1219 Do you guys want to get together tonight when this is mostly done and finalize everything/ do the video?

**Comment by jl532** [comment]
I can do it later this afternoon no problem, most of the flashy useful
functionality is already there I think. (we don't need to show all the unit
tests too though, right?)

-Jason

**Comment by jcoop1219** [comment]
Yeah probably don't need to show that. I'd be happy to meet tonight, maybe briefly around 7-8?
